on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  weekly-reprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libudunits2-dev libproj-dev libgdal-dev libgeos-dev cmake libnode-dev
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - shell: Rscript {0}
        run: |
          if (!requireNamespace("callr")) install.packages("callr")
          callr::rcmd("INSTALL", ".")
      - run: Rscript scripts/build_data.R
      - run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -A
          git commit -m "weekly data reprocess"
          git push
